-- ============================================================================
-- BodyPower Gym Management System - Real Data Backup (SQL Server & Postgres compatible)
-- Source: ASUS-VIVOBOOK\TINASQLSERVER -> BodyPowerGymDb
-- Date: 2026-09-15
-- ============================================================================

-- 1. Roles
INSERT INTO Roles (Id, Name, NormalizedName, Description, CreatedAt)
VALUES 
('admin', 'Admin', 'ADMIN', 'Full administrative system access', '2026-09-15T09:30:00Z'),
('manager', 'Manager', 'MANAGER', 'Operational front-desk access', '2026-09-15T09:30:00Z');

-- 2. Users (Preserved exact password hashes generated by ASP.NET Identity PasswordHasher)
INSERT INTO Users (Id, RoleId, FullName, Email, NormalizedEmail, Mobile, PasswordHash, AvatarUrl, IsActive, CreatedAt, UpdatedAt)
VALUES 
('u-admin-1', 'admin', 'Yogesh Gopal Mahajan', 'yogeshmahajan@gmail.com', 'YOGESHMAHAJAN@GMAIL.COM', '7410584858', 'AQAAAAIAAYagAAAAEG4xcW9wClQyCwGNHVIRFjrn1KSv0EVHrru7wNX3gpRxQDHkxkSR586HvtB9piBZeA==', NULL, 1, '2026-09-15T09:35:00Z', NULL),
('u-1789466564806', 'admin', 'Rahul Mali', 'rahulmali@gmail.com', 'RAHULMALI@GMAIL.COM', '8600276867', 'AQAAAAIAAYagAAAAEKINGkYYLvpj9LxXjRbr1G7u/ymbaAlAxS+nddbEFdYOkuH2WBQHKn8AL1X3s7nDOw==', NULL, 1, '2026-09-15T10:00:00Z', NULL),
('u-1789469393891', 'manager', 'Juber sir', 'juber@gmail.com', 'JUBER@GMAIL.COM', '9993090118', 'AQAAAAIAAYagAAAAEDj1SweV3tgtCv80d5DIX73FZiOuBlxhEO+vfEfrQAwu0M+Rwge4rp6jdP5cPAICAw==', NULL, 1, '2026-09-15T10:45:00Z', NULL);

-- 3. Membership Plans
INSERT INTO MembershipPlans (Id, Name, DurationMonths, Price, Description, IsActive, CreatedAt, UpdatedAt)
VALUES 
('p-1789465083729', 'Monthly Plan', 1, 600.00, NULL, 1, '2026-09-15T09:38:00Z', NULL),
('p-1789465216281', 'Quarterly Plan', 3, 1600.00, NULL, 1, '2026-09-15T09:40:00Z', NULL);

-- 4. Gym Settings
INSERT INTO GymSettings (Id, GymName, Phone, Address, LogoUrl, ReminderDaysJson, InactiveAfterMonths, UpdatedAt)
VALUES 
('gym-default', 'BodyPower Gym', '7410584858', 'Main Branch', NULL, '[3,1]', 2, '2026-09-15T09:43:00Z');
